/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: noyou (https://sketchfab.com/zsm123)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blade-soul-kung-fu-sword-stick-d41877a6c21a462eafd428baab752ce0
Title: Blade & Soul Kung Fu sword stick
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Kungfu(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/kung-fu/scene.gltf')
  const { actions, names } = useAnimations(animations, group)
  useEffect(() => {
    actions[names[0]].reset().fadeIn(7).play()
  }, [])



  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="11FBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <group name="Camera01" position={[-144.38, 31.22, -35.29]} rotation={[Math.PI, -1.34, Math.PI]}>
                    <group name="Object_217" />
                  </group>
                  <group name="objTwoHand13_SM" position={[92.78, 22.57, 23.11]} rotation={[1.31, 0, 0]} scale={[0.47, 0.54, 0.54]}>
                    <group name="Object_225" position={[0.29, 0, -58.01]}>
                      <mesh name="objTwoHand13_SM_fgh_0" geometry={nodes.objTwoHand13_SM_fgh_0.geometry} material={materials.material} />
                    </group>
                  </group>
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" position={[2.91, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_8" position={[2.91, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_10" position={[2.91, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_12" position={[2.91, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_14" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_16" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_18" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_20" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_22" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="objX_LynM_RedMoonSuit" position={[2.91, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="objLynM_76" position={[2.91, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="obj020001_LynM01" position={[2.91, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="objLynF18" position={[2.91, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="obj00001_JinF_Face05" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Particle_View_01" />
                  <group name="mr_Area_Omni01" position={[365.39, 1460.5, 552.74]}>
                    <group name="Object_214" rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_215" />
                    </group>
                  </group>
                  <group name="Camera01Target" position={[39, 31.22, 8.4]} />
                  <group name="Particle_View_01_1" position={[86, 0, 22.21]} />
                  <group name="objLynF1" position={[86, 0, 22.21]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="objObject01" position={[86, 0, 22.21]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="obj41002_LynM" position={[86, -0.57, 20.1]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="objLynF2" position={[86, 0, 22.21]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="������" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="���������" rotation={[-Math.PI / 2, 0, 0]} />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Material_81} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Material_86} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Material_97} skeleton={nodes.Object_11.skeleton} />
                  <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Material_32} skeleton={nodes.Object_13.skeleton} />
                  <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Material_45} skeleton={nodes.Object_15.skeleton} />
                  <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Material_116} skeleton={nodes.Object_17.skeleton} />
                  <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.zxcv} skeleton={nodes.Object_19.skeleton} />
                  <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.material} skeleton={nodes.Object_21.skeleton} />
                  <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.dfgh} skeleton={nodes.Object_23.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
